# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on:
  push:
    branches:
      - main
      
env:
   TEAM_ROLE1: Devops
   TEAM_ROLE2: Development
   TEAM_ROLE3: test
    
      

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Creating a Team
      run: | 
        echo "Login to git api "
        curl -i -u ${{ secrets.GITHUBUSER }}:${{ secrets.GITHUBPASS }} https://api.github.com/user
        echo "create a new team"
        curl \-X POST \-H "Accept: application/vnd.github.v3+json" \-H "Authorization: ${{ secrets.TOKEN }}" \https://api.github.com/orgs/ajaykatke2005/teams \-d '{"name":"Development"}' 
        echo "completed"
    - name: Updating Permissions for Devops 
      run: curl -X PATCH -H "Accept:application/vnd.github.v3+json" -H "Authorization:${{ secrets.TOKEN }}" https://api.github.com/orgs/ajaykatke2005/teams/$TEAM_ROLE1 -d '{"permission":"admin"}'
   
    - name: Updating Permissions for Devlopment 
      run: curl -X PATCH -H "Accept:application/vnd.github.v3+json" -H "Authorization:${{ secrets.TOKEN }}" https://api.github.com/orgs/ajaykatke2005/teams/$TEAM_ROLE2 -d '{"permission":"push"}'
   
    - name: Updating Permissions for Test
      run: curl -X PATCH -H "Accept:application/vnd.github.v3+json" -H "Authorization:${{ secrets.TOKEN }}" https://api.github.com/orgs/ajaykatke2005/teams/$TEAM_ROLE3 -d '{"permission":"pull"}'
      
